# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZg3stn1agwi-mzJx8mOblfS16I_XTSu
"""

import cv2

# Abra o arquivo de vídeo para leitura
v1 = cv2.VideoCapture("newfile.avi")

# Configure o arquivo de vídeo para escrita
fourcc = cv2.VideoWriter_fourcc(*'XVID')
frame_width = int(v1.get(3))
frame_height = int(v1.get(4))
v2 = cv2.VideoWriter('python.avi', fourcc, v1.get(5), (frame_width, frame_height))

while v1.isOpened():
    ret, frame = v1.read()

    if not ret:
        break

    # Crie uma máscara para os pixels que deseja modificar
    mask = np.zeros_like(frame)
    mask[-200:, -200:, :] = 255

    # Aplique a máscara ao quadro
    modified_frame = cv2.add(frame, mask)

    # Escreva o quadro modificado no arquivo de saída
    v2.write(modified_frame)

# Feche os vídeos
v1.release()
v2.release()

# Feche todas as janelas abertas do OpenCV (se houver)
cv2.destroyAllWindows()